'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { apiFetch, isSignedIn } from '@/lib/session';

// Route: /business/statements — period statements from GET /business-desk/statements. A
// statement carries a totalDue the credit desk issues, so it is read-only here; the fileUrl
// is the downloadable PDF generated by the finance system.

type Statement = {
  id: string;
  periodStart: string;
  periodEnd: string;
  totalDue: string;
  fileUrl: string | null;
};

export default function Page() {
  const router = useRouter();
  const [statements, setStatements] = useState<Statement[] | null>(null);
  const [noCompany, setNoCompany] = useState(false);

  useEffect(() => {
    if (!isSignedIn()) {
      router.push('/login');
      return;
    }
    let cancelled = false;
    apiFetch<Statement[]>('/business-desk/statements').then((result) => {
      if (cancelled) return;
      if (result.ok) setStatements(result.data);
      else if (result.status === 404) setNoCompany(true);
      else setStatements([]);
    });
    return () => {
      cancelled = true;
    };
  }, [router]);

  if (noCompany) {
    return <main style={pageStyle}><p style={{ fontSize: 13.5, color: '#5C6773' }}>This account is not linked to a company.</p></main>;
  }

  return (
    <main style={pageStyle}>
      <h1 style={headingStyle}>Statements</h1>

      {statements === null ? (
        <p style={{ fontSize: 13.5, color: '#A9B2BD', marginTop: 24 }}>Loading statements…</p>
      ) : statements.length === 0 ? (
        <p style={{ fontSize: 13.5, color: '#5C6773', marginTop: 24 }}>No statements have been issued for your account yet.</p>
      ) : (
        <table style={{ width: '100%', marginTop: 24, borderCollapse: 'collapse', fontSize: 13 }}>
          <thead>
            <tr style={{ textAlign: 'left', color: '#A9B2BD', fontWeight: 500 }}>
              <th style={thStyle}>Period</th>
              <th style={{ ...thStyle, textAlign: 'right' }}>Amount due</th>
              <th style={thStyle}>Statement</th>
            </tr>
          </thead>
          <tbody>
            {statements.map((s) => (
              <tr key={s.id} style={{ borderTop: '1px solid #EAE6DC' }}>
                <td style={tdStyle}>
                  {new Date(s.periodStart).toLocaleDateString('en-ZA')} – {new Date(s.periodEnd).toLocaleDateString('en-ZA')}
                </td>
                <td style={{ ...tdStyle, textAlign: 'right', fontWeight: 600 }}>R{Number(s.totalDue).toFixed(2)}</td>
                <td style={tdStyle}>
                  {s.fileUrl ? <a href={s.fileUrl} style={{ color: '#3E6E91' }}>Download</a> : <span style={{ color: '#A9B2BD' }}>Not available</span>}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </main>
  );
}

const pageStyle: React.CSSProperties = { maxWidth: 1000, margin: '0 auto', padding: '64px 24px' };
const headingStyle: React.CSSProperties = { fontFamily: 'Space Grotesk, sans-serif', fontSize: 26, color: '#1B2733', margin: 0 };
const thStyle: React.CSSProperties = { padding: '8px 10px', fontSize: 11.5, textTransform: 'uppercase', letterSpacing: '.06em' };
const tdStyle: React.CSSProperties = { padding: '10px', color: '#1B2733' };